export enum FactorTypeEnum {
  HYDRO_SANITARY_SYSTEM = "HYDRO_SANITARY_SYSTEM",
  RAINWATER_DRAINAGE_SYSTEM = "RAINWATER_DRAINAGE_SYSTEM",
  PAVING = "PAVING",
  ELECTRICAL_NETWORK = "ELECTRICAL_NETWORK",
  EARTHWORKS = "EARTHWORKS",
}
